version: "3.8"

services:
  xt-martinez-react-frontend:
    image: node:12-alpine
    restart: always
    volumes:
      - ./:/app:z
    ports:
      - "3000:3000"
    working_dir: /app
    stdin_open: true
