# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-1.6.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-10-20T08:51:21Z"
  labels:
    app: portfoliopod
  name: portfoliopod
spec:
  containers:
  - command:
    - docker-entrypoint.sh
    - node
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: HOSTNAME
    - name: container
      value: podman
    - name: NODE_VERSION
      value: 10.16.3
    - name: YARN_VERSION
      value: 1.17.3
    image: docker.io/library/node:10.16-alpine
    name: portfolio
    ports:
    - containerPort: 3000
      hostPort: 3000
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    tty: true
    volumeMounts:
    - mountPath: /app
      name: var-home-chmartin-Projects-XT-Martinez.github.io
    workingDir: /app
  volumes:
  - hostPath:
      path: /var/home/chmartin/Projects/XT-Martinez.github.io
      type: Directory
    name: var-home-chmartin-Projects-XT-Martinez.github.io
status: {}

